language: erlang # don't abuse the ruby servers
install:
  - sudo apt-get -qq install cmake
script:
  - mkdir _build && cd _build
  - cmake ..
  - make
  - ./fast-aleck-test
notifications:
  irc: "chat.freenode.net#nanoc"
